=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/locale-map-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->


<xs:schema targetNamespace="http://xml.spss.com/spss/mls" xmlns="http://xml.spss.com/spss/mls" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
	<xs:annotation>
		<xs:documentation xml:lang="en">Copyright 2003 SPSS Inc - All Rights Reserved.  SPSS specifically disclaims all warranties with respect to your use of this specification, expressed, implied, or otherwise, including without limitation, all warranties of merchantability and fitness for a particular purpose.  SPSS shall not be liable for any special, incidental, or consequential damages, including without limitation lost revenues or lost profits resulting from the use of the information herein.</xs:documentation>
	</xs:annotation>
	<xs:element name="client-locale">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="server-locale" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="server-locale">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="locale-map">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="client-locale" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/loclmap.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->


<!-- @version: -->
<!-- The client locale is the ISO locale name.
Executing SHOW LOCALE on the Windows client will display the ISO locale identifier
if in local mode (otherwise it shows the Server locale).
The server-locale list is tried in order after first trying the specified locale name.
If no server locale works, the SPSS Server uses the LC_ALL value of the server process.
In some cases there is no exact correspondence between Windows and Unix/Linux locales.
Note that locale identifiers are case sensitive. -->

<locale-map xmlns="http://xml.spss.com/spss/mls"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://xml.spss.com/spss/mls http://xml.spss.com/spss/mls/locale-map-1.0.xsd">
    <client-locale name="English">
        <server-locale name="en_US.cp1252"></server-locale>
        <server-locale name="en_US.iso-8859-1"></server-locale>
        <server-locale name="en_US"></server-locale>
        <server-locale name="en"></server-locale>
        <server-locale name="en_US.iso88591"></server-locale>
        <server-locale name="en_US.ISO8859-1"></server-locale>
        <server-locale name="en_US.windows-1252"></server-locale>
        <server-locale name="en_US.utf8"></server-locale>
        <server-locale name="en_US.UTF-8"></server-locale>
    </client-locale>

    <client-locale name="English-US">
        <server-locale name="en_US.cp1252"></server-locale>
        <server-locale name="en_US.iso-8859-1"></server-locale>
        <server-locale name="en_US"></server-locale>
        <server-locale name="en"></server-locale>
        <server-locale name="en_US.iso88591"></server-locale>
        <server-locale name="en_US.ISO8859-1"></server-locale>
        <server-locale name="en_US.windows-1252"></server-locale>
        <server-locale name="en_US.utf8"></server-locale>
        <server-locale name="en_US.UTF-8"></server-locale>
    </client-locale>

    <client-locale name="English-UK">
        <server-locale name="en_UK.cp1252"></server-locale>
        <server-locale name="en_UK.iso-8859-1"></server-locale>
        <server-locale name="en_GB"></server-locale>
        <server-locale name="en_UK"></server-locale>
        <server-locale name="en_GB.ISO8859-1"></server-locale>
        <server-locale name="en_GB.windows-1252"></server-locale>
        <server-locale name="en_GB.utf8"></server-locale>
        <server-locale name="en_GB.UTF-8"></server-locale>
    </client-locale>

    <client-locale name="English-Canada">
        <server-locale name="en_CA.cp1252"></server-locale>
        <server-locale name="en_CA.iso-8859-1"></server-locale>
        <server-locale name="en_CA"></server-locale>
        <server-locale name="en_CA.8859-15"></server-locale>
        <server-locale name="en_CA.windows-1252"></server-locale>
        <server-locale name="en_CA.utf8"></server-locale>
        <server-locale name="en_CA.UTF-8"></server-locale>
    </client-locale>

    <client-locale name="English-Australia">
        <server-locale name="en_AU.cp1252"></server-locale>
        <server-locale name="en_CA.iso-8859-1"></server-locale>
        <server-locale name="en_AU"></server-locale>
        <server-locale name="EN_AU"></server-locale>
        <server-locale name="en"></server-locale>
        <server-locale name="en_AU.8859-15"></server-locale>
        <server-locale name="en_AU.windows-1252"></server-locale>
        <server-locale name="en_AU.utf8"></server-locale>
        <server-locale name="en_AU.UTF-8"></server-locale>
    </client-locale>

    <client-locale name="Japanese">
        <server-locale name="ja_JP.IBM-eucJP"></server-locale>
        <server-locale name="ja_JP.cp932"></server-locale>
        <server-locale name="ja_JP.sjis"></server-locale>
        <server-locale name="ja_JP.PCK"></server-locale>
        <server-locale name="ja_JP.SJIS"></server-locale>
        <server-locale name="Ja_JP.IBM-943"></server-locale>
        <server-locale name="ja_JP.eucjp"></server-locale>
        <server-locale name="ja_JP.windows-31j"></server-locale>
        <server-locale name="ja_JP"></server-locale>
        <server-locale name="ja_JP.utf8"></server-locale>
        <server-locale name="ja_JP.UTF-8"></server-locale>
    </client-locale>

    <client-locale name="Korean">
        <server-locale name="ko_KR.cp949"></server-locale>
        <server-locale name="ko_KR.IBM-eucKR"></server-locale>
        <server-locale name="ko_KR.IBM-euckr"></server-locale>
        <server-locale name="ko_KR.euckr"></server-locale>
        <server-locale name="ko_KR"></server-locale>
        <server-locale name="ko"></server-locale>
        <server-locale name="ko_KR.EUC-KR"></server-locale>
        <server-locale name="ko_KR.utf8"></server-locale>
        <server-locale name="ko_KR.UTF-8"></server-locale>
    </client-locale>

    <client-locale name="Chinese-PRC">
        <server-locale name="zh_CN.cp936"></server-locale>
        <server-locale name="Zh_CN.GBK"></server-locale>
        <server-locale name="zh_CN.GBK"></server-locale>
        <server-locale name="zh_CN.gbk"></server-locale>
        <server-locale name="zh_CN.gb18030"></server-locale>
        <server-locale name="zh_CN.GB18030"></server-locale>
        <server-locale name="Zh_CN.GB18030"></server-locale>
        <server-locale name="zh_CN"></server-locale>
        <server-locale name="zh_CN.utf8"></server-locale>
        <server-locale name="zh_CN.UTF-8"></server-locale>
    </client-locale>

    <client-locale name="Chinese-Taiwan">
        <server-locale name="zh_HK.Big5-HKSCS"></server-locale>
        <server-locale name="zh_TW.cp950"></server-locale>
        <server-locale name="Zh_TW.big5"></server-locale>
        <server-locale name="zh_TW.BIG5"></server-locale>
        <server-locale name="zh_TW.euctw"></server-locale>
        <server-locale name="zh_TW.Big5"></server-locale>
        <server-locale name="zh_TW"></server-locale>
        <server-locale name="zh_TW.utf8"></server-locale>
        <server-locale name="zh_TW.UTF-8"></server-locale>
    </client-locale>

    <client-locale name="Vietnamese">
        <server-locale name="vi_VN.cp1258"></server-locale>
        <server-locale name="Vi_VN.IBM-1129"></server-locale>
        <server-locale name="Vi_VN"></server-locale>
        <server-locale name="vi_VN"></server-locale>
        <server-locale name="vi_VN.windows-1258"></server-locale>
        <server-locale name="vi_VN.utf8"></server-locale>
        <server-locale name="vi_VN.UTF-8"></server-locale>
    </client-locale>

    <client-locale name="Thai">
        <server-locale name="th_TH.cp874"></server-locale>
        <server-locale name="th_TH"></server-locale>
        <server-locale name="Th_TH"></server-locale>
        <server-locale name="Th_TH.windows-874"></server-locale>
        <server-locale name="th_TH.utf8"></server-locale>
        <server-locale name="th_TH.UTF-8"></server-locale>
    </client-locale>

    <client-locale name="Russian">
        <server-locale name="ru_RU.cp1251"></server-locale>
        <server-locale name="ru_RU.ISO8859-5"></server-locale>
        <server-locale name="ru_RU.8859-5"></server-locale>
        <server-locale name="ru_RU.iso88595"></server-locale>
        <server-locale name="ru"></server-locale>
        <server-locale name="ru_RU"></server-locale>
        <server-locale name="ru_RU.windows-1251"></server-locale>
        <server-locale name="ru_RU.utf8"></server-locale>
        <server-locale name="ru_RU.UTF-8"></server-locale>
    </client-locale>

    <client-locale name="Polish">
        <server-locale name="pl_PL.cp1250"></server-locale>
        <server-locale name="pl_PL.ISO8859-2"></server-locale>
        <server-locale name="pl_PL.8859-2"></server-locale>
        <server-locale name="pl_PL"></server-locale>
        <server-locale name="pl_PL.windows-1250"></server-locale>
        <server-locale name="pl_PL.utf8"></server-locale>
        <server-locale name="pl_PL.UTF-8"></server-locale>
    </client-locale>

    <client-locale name="Greek">
        <server-locale name="el_GR.cp1253"></server-locale>
        <server-locale name="el_GR.ISO8859-7"></server-locale>
        <server-locale name="el_GR.8859-7"></server-locale>
        <server-locale name="el_GR"></server-locale>
        <server-locale name="EL_GR"></server-locale>
        <server-locale name="el"></server-locale>
        <server-locale name="el_GR.windows-1253"></server-locale>
        <server-locale name="el_GR.utf8"></server-locale>
        <server-locale name="el_GR.UTF-8"></server-locale>
    </client-locale>

    <client-locale name="Hebrew">
        <server-locale name="iw_IL.cp1255"></server-locale>
        <server-locale name="iw_IL.ISO8859-8"></server-locale>
        <server-locale name="iw_IL.8859-8"></server-locale>
        <server-locale name="iw_IL"></server-locale>
        <server-locale name="he_IL"></server-locale>
        <server-locale name="iw"></server-locale>
