=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/SyntaxSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->


<xs:schema targetNamespace="http://xml.spss.com/spss/extension" 
		xmlns="http://xml.spss.com/spss/extension" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
   <xs:element name="Command" type="command-content">
  </xs:element>
  <xs:complexType name="command-content">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="Subcommand"/>
    </xs:sequence>
    <xs:attribute name="Name" use="required">
    </xs:attribute>
    <xs:attribute name="Language" default="Syntax">
       <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Python"/>
          <xs:enumeration value="R"/>
          <xs:enumeration value="Syntax"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="IsArbitrary" default="No">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="True"/>
          <xs:enumeration value="False"/>
          <xs:enumeration value="Yes"/>
          <xs:enumeration value="No"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="EndRequired" default="None">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="None"/>
          <xs:enumeration value="Command"/>
          <xs:enumeration value="Block"/>
         </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="EndStatement"/>
  </xs:complexType>
  <xs:element name="Subcommand" type="subcommand-content">
  </xs:element>
  <xs:complexType name="subcommand-content">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="Parameter"/>
    </xs:sequence>
    <xs:attribute name="Name" use="required"/>
    <xs:attribute name="Occurrence" default="Optional">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Required"/>
          <xs:enumeration value="Optional"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="IsArbitrary" default="No">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="True"/>
          <xs:enumeration value="False"/>
          <xs:enumeration value="Yes"/>
          <xs:enumeration value="No"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="EqualsSign" default="None">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Required"/>
          <xs:enumeration value="Optional"/>
          <xs:enumeration value="None">
          </xs:enumeration>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:element name="Parameter" type="parameter-content">
  </xs:element>
  <xs:complexType name="parameter-content">
    <xs:sequence maxOccurs="unbounded" minOccurs="0">
      <xs:element  name="EnumValue">
        <xs:complexType>
          <xs:attributeGroup ref="enumValue-content"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Name" use="required">
    </xs:attribute>
    <xs:attribute name="ParameterType" default="Keyword">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="DatasetName"/>
          <xs:enumeration value="Integer"/>
          <xs:enumeration value="IntegerList"/>
          <xs:enumeration value="Keyword"/>
          <xs:enumeration value="KeywordList"/>
          <xs:enumeration value="LeadingToken"/>
          <xs:enumeration value="Number"/>
          <xs:enumeration value="NumberList"/>
          <xs:enumeration value="QuotedString"/>
          <xs:enumeration value="TokenList"/>
          <xs:enumeration value="VariableName"/>
          <xs:enumeration value="VariableNameList"/>
          <xs:enumeration value="InputFile"/>
          <xs:enumeration value="OutputFile"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="EqualsSign" default="None">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Required"/>
          <xs:enumeration value="Optional"/>
          <xs:enumeration value="None">
          </xs:enumeration>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:attributeGroup name="enumValue-content">
    <xs:attribute name="Name" use="required">
    </xs:attribute>
  </xs:attributeGroup>
</xs:schema>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/CSTABULATE.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->

 <!-- Created 4/30/08 -->
<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension http://xml.spss.com/spss/extension/SyntaxSchema.xsd"
    Name="CSTABULATE" EndRequired="None" IsArbitrary="No" Language="Syntax"> 
<Subcommand Name="PLAN" EqualsSign="None">
       <Parameter Name="FILE" EqualsSign="Required" ParameterType="Keyword"/>
</Subcommand>
    <Subcommand Name="JOINTPROB" EqualsSign="None">
        <Parameter Name="FILE" EqualsSign="Required" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="TABLES" EqualsSign="None">
        <Parameter Name="VARIABLES" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="BY" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="CELLS" EqualsSign="None">
        <Parameter Name="POPSIZE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="ROWPCT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="COLPCT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="TABLEPCT" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="STATISTICS" EqualsSign="None">
        <Parameter Name="SE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CV" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="DEFF" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="DEFFSQRT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CIN" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="COUNT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CUMULATIVE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="EXPECTED" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="RESID" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="ASRESID" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
     <Subcommand Name="TEST" EqualsSign="None">
         <Parameter Name="HOMOGENEITY" EqualsSign="None" ParameterType="Keyword"/>
         <Parameter Name="INDEPENDENCE" EqualsSign="None" ParameterType="Keyword"/>
         <Parameter Name="ODDSRATIO" EqualsSign="None" ParameterType="Keyword"/>
         <Parameter Name="RELRISK" EqualsSign="None" ParameterType="Keyword"/>
         <Parameter Name="RISKDIFF" EqualsSign="None" ParameterType="Keyword"/>
     </Subcommand>
    <Subcommand Name="SUBPOP" EqualsSign="None">
        <Parameter Name="TABLE" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="BY" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="DISPLAY" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="LAYERED"/>
            <EnumValue Name="SEPARATE"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="MISSING" EqualsSign="None">
        <Parameter Name="SCOPE" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="TABLE"/>
            <EnumValue Name="LISTWISE"/>
        </Parameter>
        <Parameter Name="CLASSMISSING" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="EXCLUDE"/>
            <EnumValue Name="INCLUDE"/>
        </Parameter>
    </Subcommand>
</Command>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/AREG.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->


<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension http://xml.spss.com/spss/extension/SyntaxSchema.xsd"
    Name="AREG" EndRequired="None" IsArbitrary="No" Language="Syntax">
    <Subcommand Name="GLOBAL_PARAMS" EqualsSign="None">
        <Parameter Name="VARIABLES" EqualsSign="Optional" ParameterType="Keyword"/>
        <Parameter Name="WITH" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="METHOD" EqualsSign="Optional">
        <Parameter Name="PW" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CO" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="ML" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="CONSTANT" EqualsSign="None"/>
    <Subcommand Name="NOCONSTANT" EqualsSign="None"/>
    <Subcommand Name="RHO" EqualsSign="Optional"/>
    <Subcommand Name="MXITER" EqualsSign="Optional"/>
    <Subcommand Name="APPLY" EqualsSign="Optional">
        <Parameter Name="SPECIFICATIONS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="INITIAL" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="FIT" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
</Command>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/ANACOR.xml
<?xml version="1.0"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->

 <!-- Updated 4/28/08 -->
<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension http://xml.spss.com/spss/extension/SyntaxSchema.xsd"
    xmlns:p1="http://xml.spss.com/spss/extension" Name="ANACOR" EndRequired="None" IsArbitrary="No"
    Language="Syntax">
    <Subcommand Name="GLOBAL_PARAMS">
        <Parameter Name="TABLE" EqualsSign="Optional" ParameterType="Keyword">
            <EnumValue Name="BY"/>
            <EnumValue Name="ALL"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="DIMENSION" EqualsSign="Optional"/>
    <Subcommand Name="NORMALIZATION" EqualsSign="Optional">
        <Parameter Name="CANONICAL" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="PRINCIPAL" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="RPRINCIPAL" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CPRINCIPAL" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="VARIANCES" EqualsSign="Optional">
        <Parameter Name="SINGULAR" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="ROWS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="COLUMNS" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="PRINT" EqualsSign="Optional">
        <Parameter Name="TABLE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="PROFILES" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SCORES" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CONTRIBUTIONS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="DEFAULT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="PERMUTATION" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="NONE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="PLOT" EqualsSign="Optional">
        <Parameter Name="NDIM" EqualsSign="Optional" ParameterType="Keyword">
            <EnumValue Name="ALL"/>
            <EnumValue Name="MAX"/>
        </Parameter>
        <Parameter Name="ROWS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="COLOMNS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="DEFAULT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="TRROWS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="TRCOLUMNS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="JOINT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="NONE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="MATRIX" EqualsSign="Optional">
        <Parameter Name="OUT" EqualsSign="Optional" ParameterType="Keyword">
            <EnumValue Name="SCORE"/>
        </Parameter>
        <Parameter Name="VARIANCE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
</Command>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/VARCOMP.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->

 <!-- Created 5/22/08 -->
<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension http://xml.spss.com/spss/extension/SyntaxSchema.xsd"
    Name="VARCOMP" EndRequired="None" IsArbitrary="No" Language="Syntax">
    <Subcommand Name="GLOBAL_PARAMS" EqualsSign="None">
        <Parameter Name="BY" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="WITH" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="RANDOM" EqualsSign="Optional"/>
    <Subcommand Name="METHOD" EqualsSign="Optional">
        <Parameter Name="MINQUE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="ML" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="REML" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SSTYPE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="INTERCEPT" EqualsSign="Optional">
        <Parameter Name="INCLUDE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="EXCLUDE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="MISSING" EqualsSign="Optional">
        <Parameter Name="INCLUDE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="EXCLUDE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="REGWGT" EqualsSign="Optional"/>
    <Subcommand Name="CRITERIA" EqualsSign="Optional">
        <Parameter Name="CONVERGE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="EPS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="ITERATE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="PRINT" EqualsSign="Optional">
        <Parameter Name="EMS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="HISTORY" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SS" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="OUTFILE" EqualsSign="Optional">
        <Parameter Name="VAREST" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="COVB" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CORB" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="DESIGN" EqualsSign="Optional">
        <Parameter Name="INTERCEPT" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
</Command>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/CORRESPONDENCE.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->

 <!-- Created 4/25/08 -->
<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension http://xml.spss.com/spss/extension/SyntaxSchema.xsd"
    Name="CORRESPONDENCE" Language="Syntax" IsArbitrary="No" EndRequired="None">
    <Subcommand Name="GLOBAL_PARAMS">
        <Parameter Name="TABLE" EqualsSign="Optional" ParameterType="Keyword">
            <EnumValue Name="BY"/>
            <EnumValue Name="ALL"/>
        </Parameter>
        <Parameter Name="OVERWRITE" EqualsSign="Optional" ParameterType="Keyword">
            <EnumValue Name="NO"/>
            <EnumValue Name="YES"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="TABLE" EqualsSign="Optional">
        <Parameter Name="BY" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="ALL" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="SUPPLEMENTARY" EqualsSign="Optional">
        <Parameter Name="ROW" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="COLUMN" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="EQUAL" EqualsSign="Optional">
        <Parameter Name="ROW" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="COLUMN" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="MEASURE" EqualsSign="Optional">
        <Parameter Name="CHISQ" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="EUCLID" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="STANDARDIZE" EqualsSign="Optional">
        <Parameter Name="RMEAN" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CMEAN" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="RCMEAN" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="RSUM" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CSUM" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="DIMENSIONS" EqualsSign="Optional"/>
    <Subcommand Name="NORMALIZATION" EqualsSign="Optional">
        <Parameter Name="SYMMETRICAL" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="PRINCIPAL" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="RPRINCIPAL" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CPRINCIPAL" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="PRINT" EqualsSign="Optional">
        <Parameter Name="TABLE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="RPROF" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CPROF" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="RPOINTS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CPOINTS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="RCONF" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CCONF" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="PERMUTATION" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="DEFAULT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="NONE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="PLOT" EqualsSign="Optional">
        <Parameter Name="NDIM" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="RPOINTS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CPOINTS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="TRROWS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="TRCOLUMNS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="BIPLOT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="NONE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="OUTFILE" EqualsSign="Optional">
        <Parameter Name="SCORE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="VARIANCE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
</Command>
