=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/SyntaxSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->


<xs:schema targetNamespace="http://xml.spss.com/spss/extension" 
		xmlns="http://xml.spss.com/spss/extension" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
   <xs:element name="Command" type="command-content">
  </xs:element>
  <xs:complexType name="command-content">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="Subcommand"/>
    </xs:sequence>
    <xs:attribute name="Name" use="required">
    </xs:attribute>
    <xs:attribute name="Language" default="Syntax">
       <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Python"/>
          <xs:enumeration value="R"/>
          <xs:enumeration value="Syntax"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="IsArbitrary" default="No">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="True"/>
          <xs:enumeration value="False"/>
          <xs:enumeration value="Yes"/>
          <xs:enumeration value="No"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="EndRequired" default="None">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="None"/>
          <xs:enumeration value="Command"/>
          <xs:enumeration value="Block"/>
         </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="EndStatement"/>
  </xs:complexType>
  <xs:element name="Subcommand" type="subcommand-content">
  </xs:element>
  <xs:complexType name="subcommand-content">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="Parameter"/>
    </xs:sequence>
    <xs:attribute name="Name" use="required"/>
    <xs:attribute name="Occurrence" default="Optional">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Required"/>
          <xs:enumeration value="Optional"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="IsArbitrary" default="No">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="True"/>
          <xs:enumeration value="False"/>
          <xs:enumeration value="Yes"/>
          <xs:enumeration value="No"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="EqualsSign" default="None">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Required"/>
          <xs:enumeration value="Optional"/>
          <xs:enumeration value="None">
          </xs:enumeration>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:element name="Parameter" type="parameter-content">
  </xs:element>
  <xs:complexType name="parameter-content">
    <xs:sequence maxOccurs="unbounded" minOccurs="0">
      <xs:element  name="EnumValue">
        <xs:complexType>
          <xs:attributeGroup ref="enumValue-content"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Name" use="required">
    </xs:attribute>
    <xs:attribute name="ParameterType" default="Keyword">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="DatasetName"/>
          <xs:enumeration value="Integer"/>
          <xs:enumeration value="IntegerList"/>
          <xs:enumeration value="Keyword"/>
          <xs:enumeration value="KeywordList"/>
          <xs:enumeration value="LeadingToken"/>
          <xs:enumeration value="Number"/>
          <xs:enumeration value="NumberList"/>
          <xs:enumeration value="QuotedString"/>
          <xs:enumeration value="TokenList"/>
          <xs:enumeration value="VariableName"/>
          <xs:enumeration value="VariableNameList"/>
          <xs:enumeration value="InputFile"/>
          <xs:enumeration value="OutputFile"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="EqualsSign" default="None">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Required"/>
          <xs:enumeration value="Optional"/>
          <xs:enumeration value="None">
          </xs:enumeration>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:attributeGroup name="enumValue-content">
    <xs:attribute name="Name" use="required">
    </xs:attribute>
  </xs:attributeGroup>
</xs:schema>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/OLAP CUBES.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->

 <!-- Created 5/15/08 -->
<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension http://xml.spss.com/spss/extension/SyntaxSchema.xsd"
    Name="OLAP CUBES" EndRequired="None" IsArbitrary="No" Language="Syntax">
    <Subcommand Name="GLOBAL_PARAMS" EqualsSign="None">
        <Parameter Name="BY" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="CELLS" EqualsSign="Optional">
        <Parameter Name="MEAN" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="COUNT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="STDDEV" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="NPCT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SPCT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SUM" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="MEDIAN" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="GMEDIAN" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SEMEAN" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="MIN" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="MAX" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="RANGE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="VARIANCE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="KURT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SEKURT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SKEW" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SESKEW" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="FIRST" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="LAST" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="NPCT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SPCT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="HARMONIC" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="GEOMETRIC" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="DEFAULT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="ALL" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="NONE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="CREATE" EqualsSign="None">
        <Parameter Name="DEFAULT" EqualsSign="Optional" ParameterType="Keyword"/>
        <Parameter Name="GAC" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="GPC" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="GAC GPC" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="VAC" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="VPC" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="VAC VPC" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="TITLE" EqualsSign="Optional">
        <Parameter Name="FOOTNOTE" EqualsSign="Optional" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="HIDESMALLCOUNTS" EqualsSign="None">
        <Parameter Name="COUNT" EqualsSign="Optional" ParameterType="Keyword"/>
    </Subcommand>
</Command>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/HILOGLINEAR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->


<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension file:/C:/temp/schema/SyntaxSchema.xsd"
    Name="HILOGLINEAR" EndRequired="None" IsArbitrary="No" Language="Syntax">
    <Subcommand Name="GLOBAL_PARAMS">
        <Parameter Name="ALL" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="METHOD" EqualsSign="Optional">
        <Parameter Name="BACKWARD" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="MAXORDER" EqualsSign="Optional"/>
    <Subcommand Name="CRITERIA" EqualsSign="Optional">
        <Parameter Name="CONVERGE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="ITERATE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="P" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="DELTA" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="MAXSTEPS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="DEFAULT" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="CWEIGHT" EqualsSign="Optional"/>
    <Subcommand Name="PRINT" EqualsSign="Optional">
        <Parameter Name="FREQ" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="RESID" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="ESTIM" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="ASSOCIATION" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="DEFAULT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="ALL" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="NONE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="PLOT" EqualsSign="Optional">
        <Parameter Name="NONE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="DEFAULT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="RESID" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="NORMPROB" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="ALL" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="MISSING" EqualsSign="Optional">
        <Parameter Name="EXCLUDE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="INCLUDE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="DESIGN" EqualsSign="Optional"/>
</Command>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/ARIMA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->


<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension http://xml.spss.com/spss/extension/SyntaxSchema.xsd"
    Name="ARIMA" EndRequired="None" IsArbitrary="No" Language="Syntax">
    <Subcommand Name="GLOBAL_PARAMS" EqualsSign="None">
        <Parameter Name="VARIABLES" EqualsSign="Optional" ParameterType="Keyword"/>
        <Parameter Name="WITH" EqualsSign="Optional" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="MODEL" EqualsSign="Optional">
        <Parameter Name="CONSTANT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="NOCONSTANT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="NOLOG" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="LG10" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="LOG" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="LN" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="P" EqualsSign="Optional"/>
    <Subcommand Name="D" EqualsSign="Optional"/>
    <Subcommand Name="Q" EqualsSign="Optional"/>
    <Subcommand Name="SP" EqualsSign="Optional"/>
    <Subcommand Name="SD" EqualsSign="Optional"/>
    <Subcommand Name="SQ" EqualsSign="Optional"/>
    <Subcommand Name="AR" EqualsSign="Optional"/>
    <Subcommand Name="MA" EqualsSign="Optional"/>
    <Subcommand Name="SAR" EqualsSign="Optional"/>
    <Subcommand Name="SMA" EqualsSign="Optional"/>
    <Subcommand Name="REG" EqualsSign="Optional"/>
    <Subcommand Name="CON" EqualsSign="Optional"/>
    <Subcommand Name="MXITER" EqualsSign="Optional"/>
    <Subcommand Name="MXLAMB" EqualsSign="Optional"/>
    <Subcommand Name="SSQPCT" EqualsSign="Optional"/>
    <Subcommand Name="PAREPS" EqualsSign="Optional"/>
    <Subcommand Name="CINPCT" EqualsSign="Optional"/>
    <Subcommand Name="APPLY" EqualsSign="Optional">
        <Parameter Name="SPECIFICATIONS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="INITIAL" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="FIT" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="FORECAST" EqualsSign="Optional">
        <Parameter Name="EXACT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CLS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="AUTOINIT" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
</Command>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/MATCH FILES.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->

 <!-- Created 5/12/08 -->
<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension file:/C:/temp/schema/SyntaxSchema.xsd"
    Name="MATCH FILES" EndRequired="None" IsArbitrary="No" Language="Syntax">
    <Subcommand Name="GLOBAL_PARAMS">
        <Parameter Name="FILE" EqualsSign="Optional" ParameterType="Keyword"/>
        <Parameter Name="TABLE" EqualsSign="Optional" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="FILE" EqualsSign="Optional"/>
    <Subcommand Name="TABLE" EqualsSign="Optional"/>
    <Subcommand Name="RENAME" EqualsSign="Optional"/>
    <Subcommand Name="IN" EqualsSign="Optional"/>
    <Subcommand Name="FILE" EqualsSign="Optional">
        <Parameter Name="TABLE" EqualsSign="Optional" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="BY" EqualsSign="None"/>
    <Subcommand Name="MAP" EqualsSign="None"/>
    <Subcommand Name="KEEP" EqualsSign="Optional">
        <Parameter Name="ALL" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="DROP" EqualsSign="Optional"/>
    <Subcommand Name="FIRST" EqualsSign="Optional"/>
    <Subcommand Name="LAST" EqualsSign="Optional"/>
</Command>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/OMS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2012                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->

 <!-- Created 5/15/08 -->
<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension http://xml.spss.com/spss/extension/SyntaxSchema.xsd"
    Name="OMS" EndRequired="None" IsArbitrary="No" Language="Syntax"> 
    <Subcommand Name="SELECT" EqualsSign="None">
        <Parameter Name="CHARTS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="TEXTS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="LOGS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="WARNINGS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="TABLES" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="HEADINGS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="TREES" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="ALL" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="EXCEPT" EqualsSign="Optional" ParameterType="Keyword"/>
        <Parameter Name="MODELS" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="IF" EqualsSign="None">
        <Parameter Name="COMMANDS" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="SUBTYPES" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="LABELS" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="INSTANCES" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="LAST"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="EXCEPTIF" EqualsSign="None">
        <Parameter Name="COMMANDS" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="SUBTYPES" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="LABELS" EqualsSign="Required" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="DESTINATION" EqualsSign="None">
        <Parameter Name="FORMAT" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="OXML"/>
            <EnumValue Name="HTML"/>
            <EnumValue Name="TEXT"/>
            <EnumValue Name="TABTEXT"/>
            <EnumValue Name="SAV"/>
            <EnumValue Name="SPV"/>
            <EnumValue Name="DOC"/>
            <EnumValue Name="PDF"/>
            <EnumValue Name="SPW"/>
            <EnumValue Name="XLS"/>
            <EnumValue Name="XLSX"/>
        </Parameter>
        <Parameter Name="OUTFILE" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="XMLWORKSPACE" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="OUTPUTSET" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="SUBTYPES"/>
            <EnumValue Name="LABELS"/>
            <EnumValue Name="FOLDER"/>
        </Parameter>
        <Parameter Name="VIEWER" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="YES"/>
            <EnumValue Name="NO"/>
        </Parameter>
        <Parameter Name="NUMBERED" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="IMAGES" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="YES"/>
            <EnumValue Name="NO"/>
        </Parameter>
        <Parameter Name="IMAGEFORMAT" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="PNG"/>
            <EnumValue Name="JPG"/>
            <EnumValue Name="EMF"/>
            <EnumValue Name="BMP"/>
            <EnumValue Name="VML"/>
        </Parameter>
        <Parameter Name="IMAGEROOT" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="CHARTSIZE" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="IMAGEMAP" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="YES"/>
            <EnumValue Name="NO"/>
        </Parameter>
        <Parameter Name="TREEFORMAT" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="XML"/>
            <EnumValue Name="IMAGE"/>
        </Parameter>
        <Parameter Name="CHARTFORMAT" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="XML"/>
            <EnumValue Name="IMAGE"/>
        </Parameter>
        <Parameter Name="MODELFORMAT" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="XML"/>
            <EnumValue Name="IMAGE"/>
        </Parameter>
        <Parameter Name="TABLES" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="PIVOTABLE"/>
            <EnumValue Name="STATIC"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="COLUMNS" EqualsSign="None">
        <Parameter Name="DIMNAMES" EqualsSign="Required"/>
        <Parameter Name="SEQUENCE" EqualsSign="Required">
            <EnumValue Name="R1"/>
            <EnumValue Name="R2"/>
            <EnumValue Name="RALL"/>
            <EnumValue Name="C1"/>
            <EnumValue Name="C2"/>
            <EnumValue Name="CALL"/>
            <EnumValue Name="L1"/>
            <EnumValue Name="L2"/>
            <EnumValue Name="LALL"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="TAG" EqualsSign="Required"/>
    <Subcommand Name="NOWARN" EqualsSign="None"/>
</Command>
