=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/SyntaxSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->


<xs:schema targetNamespace="http://xml.spss.com/spss/extension" 
		xmlns="http://xml.spss.com/spss/extension" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
   <xs:element name="Command" type="command-content">
  </xs:element>
  <xs:complexType name="command-content">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="Subcommand"/>
    </xs:sequence>
    <xs:attribute name="Name" use="required">
    </xs:attribute>
    <xs:attribute name="Language" default="Syntax">
       <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Python"/>
          <xs:enumeration value="R"/>
          <xs:enumeration value="Syntax"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="IsArbitrary" default="No">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="True"/>
          <xs:enumeration value="False"/>
          <xs:enumeration value="Yes"/>
          <xs:enumeration value="No"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="EndRequired" default="None">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="None"/>
          <xs:enumeration value="Command"/>
          <xs:enumeration value="Block"/>
         </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="EndStatement"/>
  </xs:complexType>
  <xs:element name="Subcommand" type="subcommand-content">
  </xs:element>
  <xs:complexType name="subcommand-content">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" ref="Parameter"/>
    </xs:sequence>
    <xs:attribute name="Name" use="required"/>
    <xs:attribute name="Occurrence" default="Optional">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Required"/>
          <xs:enumeration value="Optional"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="IsArbitrary" default="No">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="True"/>
          <xs:enumeration value="False"/>
          <xs:enumeration value="Yes"/>
          <xs:enumeration value="No"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="EqualsSign" default="None">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Required"/>
          <xs:enumeration value="Optional"/>
          <xs:enumeration value="None">
          </xs:enumeration>
       </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:element name="Parameter" type="parameter-content">
  </xs:element>
  <xs:complexType name="parameter-content">
    <xs:sequence maxOccurs="unbounded" minOccurs="0">
      <xs:element  name="EnumValue">
        <xs:complexType>
          <xs:attributeGroup ref="enumValue-content"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Name" use="required">
    </xs:attribute>
    <xs:attribute name="ParameterType" default="Keyword">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="DatasetName"/>
          <xs:enumeration value="Integer"/>
          <xs:enumeration value="IntegerList"/>
          <xs:enumeration value="Keyword"/>
          <xs:enumeration value="KeywordList"/>
          <xs:enumeration value="LeadingToken"/>
          <xs:enumeration value="Number"/>
          <xs:enumeration value="NumberList"/>
          <xs:enumeration value="QuotedString"/>
          <xs:enumeration value="TokenList"/>
          <xs:enumeration value="VariableName"/>
          <xs:enumeration value="VariableNameList"/>
          <xs:enumeration value="InputFile"/>
          <xs:enumeration value="OutputFile"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="EqualsSign" default="None">
      <xs:simpleType>
        <xs:restriction base="xs:token">
          <xs:enumeration value="Required"/>
          <xs:enumeration value="Optional"/>
          <xs:enumeration value="None">
          </xs:enumeration>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>
  <xs:attributeGroup name="enumValue-content">
    <xs:attribute name="Name" use="required">
    </xs:attribute>
  </xs:attributeGroup>
</xs:schema>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/BOOTSTRAP.xml
<?xml version="1.0"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->


<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension http://xml.spss.com/spss/extension/SyntaxSchema.xsd"
    xmlns:p1="http://xml.spss.com/spss/extension" Name="BOOTSTRAP" EndRequired="None"
    IsArbitrary="No" Language="Syntax">
    <Subcommand Name="SAMPLING">
        <Parameter Name="METHOD" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="SIMPLE"/>
            <EnumValue Name="STRATIFIED"/>
            <EnumValue Name="RESIDUAL"/>
            <EnumValue Name="WILD"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="VARIABLES">
        <Parameter Name="TARGET" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="INPUT" EqualsSign="Required" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="CRITERIA">
        <Parameter Name="CILEVEL" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="CITYPE" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="PERCENTILE"/>
            <EnumValue Name="BCA"/>
        </Parameter>
        <Parameter Name="NSAMPLES" EqualsSign="Required" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="MISSING">
        <Parameter Name="USERMISSING" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="EXCLUDE"/>
            <EnumValue Name="INCLUDE"/>
        </Parameter>
    </Subcommand>
</Command>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/MIXED.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->

 <!-- Created 5/12/08 -->
<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension file:/C:/temp/schema/SyntaxSchema.xsd"
    Name="MIXED" EndRequired="None" IsArbitrary="No" Language="Syntax">
    <Subcommand Name="GLOBAL_PARAMS">
        <Parameter Name="BY" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="WITH" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="CRITERIA" EqualsSign="Optional">
        <Parameter Name="CIN" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="HCONVERGE" EqualsSign="None" ParameterType="Keyword">
            <EnumValue Name="ABSOLUTE"/>
            <EnumValue Name="RELATIVE"/>
        </Parameter>
        <Parameter Name="LCONVERGE" EqualsSign="None" ParameterType="Keyword">
            <EnumValue Name="ABSOLUTE"/>
            <EnumValue Name="RELATIVE"/>
        </Parameter>
        <Parameter Name="MXITER" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="MXSTEP" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="PCONVERGE" EqualsSign="None" ParameterType="Keyword">
            <EnumValue Name="ABSOLUTE"/>
            <EnumValue Name="RELATIVE"/>
        </Parameter>
        <Parameter Name="SCORING" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SINGULAR" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="EMMEANS" EqualsSign="Optional">
        <Parameter Name="TABLES" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="OVERALL" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="WITH" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="COMPARE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="REFCAT" EqualsSign="None" ParameterType="Keyword">
            <EnumValue Name="FIRST"/>
            <EnumValue Name="LAST"/>
        </Parameter>
        <Parameter Name="ADJ" EqualsSign="None" ParameterType="Keyword">
            <EnumValue Name="LSD"/>
            <EnumValue Name="BONFERRONI"/>
            <EnumValue Name="SIDAK"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="FIXED" EqualsSign="Optional">
        <Parameter Name="NOINT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SSTYPE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="METHOD" EqualsSign="Optional">
        <Parameter Name="ML" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="REML" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="MISSING" EqualsSign="Optional">
        <Parameter Name="EXCLUDE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="INCLUDE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="PRINT" EqualsSign="Optional">
        <Parameter Name="CORB" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="COVB" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CPS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="DESCRIPTIVES" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="G" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="HISTORY" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="LMATRIX" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="R" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SOLUTION" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="TESTCOV" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="RANDOM" EqualsSign="Optional">
        <Parameter Name="SUBJECT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="COVTYPE" EqualsSign="None" ParameterType="Keyword">
            <EnumValue Name="VC"/>
            <EnumValue Name="AD1"/>
            <EnumValue Name="AR1"/>
            <EnumValue Name="ARH1"/>
            <EnumValue Name="ARMA11"/>
            <EnumValue Name="CS"/>
            <EnumValue Name="CSH"/>
            <EnumValue Name="CSR"/>
            <EnumValue Name="DIAG"/>
            <EnumValue Name="FA1"/>
            <EnumValue Name="FAH1"/>
            <EnumValue Name="HF"/>
            <EnumValue Name="ID"/>
            <EnumValue Name="TP"/>
            <EnumValue Name="TPH"/>
            <EnumValue Name="UN"/>
            <EnumValue Name="UNR"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="REGWGT" EqualsSign="Optional"/>
    <Subcommand Name="REPEATED" EqualsSign="Optional">
        <Parameter Name="SUBJECT" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="COVTYPE" EqualsSign="None" ParameterType="Keyword">
            <EnumValue Name="DIAG"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="SAVE" EqualsSign="Optional">
        <Parameter Name="FIXPRED" EqualsSign="None" ParameterType="Keyword"/>            
        <Parameter Name="PRED" EqualsSign="None" ParameterType="Keyword"/>            
        <Parameter Name="RESID" EqualsSign="None" ParameterType="Keyword"/>            
        <Parameter Name="SEFIXP" EqualsSign="None" ParameterType="Keyword"/>            
        <Parameter Name="SEPRED" EqualsSign="None" ParameterType="Keyword"/>            
        <Parameter Name="DFFIXP" EqualsSign="None" ParameterType="Keyword"/>            
        <Parameter Name="DFPRED" EqualsSign="None" ParameterType="Keyword"/>            
    </Subcommand>
    <Subcommand Name="TEST" EqualsSign="Optional">
        <Parameter Name="ALL" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>

</Command>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/SELECTPRED.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->

 <!-- Created 5/21/08 -->
<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension http://xml.spss.com/spss/extension/SyntaxSchema.xsd"
    Name="SELECTPRED" Language="Syntax" IsArbitrary="No" EndRequired="None">
    <Subcommand Name="GLOBAL_PARAMS" EqualsSign="None">
        <Parameter Name="MLEVEL" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="S"/>
            <EnumValue Name="O"/>
            <EnumValue Name="N"/>
        </Parameter>
        <Parameter Name="BY" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="WITH" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="EXCEPT" EqualsSign="None">
        <Parameter Name="VARIABLES" EqualsSign="Required" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="SCREENING" EqualsSign="None">
        <Parameter Name="STATUS" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="ON"/>
            <EnumValue Name="OFF"/>
        </Parameter>
        <Parameter Name="PCTMISSING" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="PCTEQUAL" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="PCTUNEQUAL" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="STDDEV" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="CV" EqualsSign="Required" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="CRITERIA" EqualsSign="None">
        <Parameter Name="SIZE" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="AUTO"/>
        </Parameter>
        <Parameter Name="PCUTOFF" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="RANKING" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="PEARSONCHISQ"/>
            <EnumValue Name="LRCHISQ"/>
            <EnumValue Name="CRAMERSV"/>
            <EnumValue Name="LAMBDA"/>
        </Parameter>
        <Parameter Name="TIMER" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="SHOWUNSELECTED" EqualsSign="Required" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="MISSING" EqualsSign="None">
        <Parameter Name="USERMISSING" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="EXCLUDE"/>
            <EnumValue Name="INCLUDE"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="PRINT" EqualsSign="None">
        <Parameter Name="CPS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="EXCLUDED" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SELECTED" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="NONE" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SUMMARY" EqualsSign="None" ParameterType="Keyword">
            <EnumValue Name="PEARSONCHISQ"/>
            <EnumValue Name="LRCHISQ"/>
            <EnumValue Name="CRAMERSV"/>
            <EnumValue Name="LAMBDA"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="PLOT" EqualsSign="None">
        <Parameter Name="SUMMARY" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
</Command>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/CSPLAN ANALYSIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->

 <!-- Created 4/30/08 -->
<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension http://xml.spss.com/spss/extension/SyntaxSchema.xsd" Name="CSPLAN ANALYSIS" EndRequired="None" IsArbitrary="No" Language="Syntax">
  <Subcommand Name="PLAN" EqualsSign="None">
        <Parameter Name="FILE" EqualsSign="Required" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="PLANVARS" EqualsSign="None">
        <Parameter Name="ANALYSISWEIGHT" EqualsSign="Required" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="SRSESTIMATOR" EqualsSign="None">
        <Parameter Name="TYPE" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="WOR"/>
            <EnumValue Name="WR"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="PRINT" EqualsSign="None">
        <Parameter Name="PLAN" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="MATRIX" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="DESIGN" EqualsSign="None">
        <Parameter Name="STAGELABEL" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="STRATA" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="CLUSTER" EqualsSign="Required" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="ESTIMATOR" EqualsSign="None">
        <Parameter Name="TYPE" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="EQUAL_WOR"/>
            <EnumValue Name="UNEQUAL_WOR"/>
            <EnumValue Name="WR"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="POPSIZE" EqualsSign="None">
        <Parameter Name="VALUE" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="VARIABLE" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="MATRIX" EqualsSign="Required" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="INCLPROB" EqualsSign="None">
         <Parameter Name="VALUE" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="VARIABLE" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="MATRIX" EqualsSign="Required" ParameterType="Keyword"/>       
    </Subcommand>
</Command>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/NAIVEBAYES.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->

 <!-- Create 5/14/08 -->
<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension http://xml.spss.com/spss/extension/SyntaxSchema.xsd"
    Name="NAIVEBAYES" EndRequired="None" IsArbitrary="No" Language="Syntax"> 
    <Subcommand Name="GLOBAL_PARAMS" EqualsSign="None">
        <Parameter Name="BY" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="WITH" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="EXCEPT" EqualsSign="None">
        <Parameter Name="VARIABLES" EqualsSign="Optional" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="FORCE" EqualsSign="None">
        <Parameter Name="FACTORS" EqualsSign="Optional" ParameterType="Keyword"/>
        <Parameter Name="COVARIATES" EqualsSign="Optional" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="TRAININGSAMPLE" EqualsSign="None">
        <Parameter Name="PERCENT" EqualsSign="Optional" ParameterType="Keyword"/>
        <Parameter Name="VARIABLES" EqualsSign="Optional" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="SUBSET" EqualsSign="None">
        <Parameter Name="MAXSIZE" EqualsSign="Optional" ParameterType="Keyword">
            <EnumValue Name="AUTO"/>
        </Parameter>
        <Parameter Name="BESTSUBSET" EqualsSign="Optional" ParameterType="Keyword">
            <EnumValue Name="PSEUDOBIC"/>
            <EnumValue Name="TESTDATA"/>
        </Parameter>
        <Parameter Name="EXACTSIZE" EqualsSign="Optional" ParameterType="Keyword"/>
        <Parameter Name="NOSELECTION" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="CRITERIA" EqualsSign="None">
        <Parameter Name="BINS" EqualsSign="Optional" ParameterType="Keyword"/>
        <Parameter Name="MEMALLOCATE" EqualsSign="Optional" ParameterType="Keyword"/>
        <Parameter Name="TIMER" EqualsSign="Optional" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="MISSING" EqualsSign="None">
        <Parameter Name="USERMISSING" EqualsSign="Optional" ParameterType="Keyword">
            <EnumValue Name="EXCLUDE"/>
            <EnumValue Name="INCLUDE"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="PRINT" EqualsSign="None">
        <Parameter Name="CPS" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="EXCLUDED" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SUMMARY" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="SELECTED" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="CLASSIFICATION" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="NONE" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="SAVE" EqualsSign="None">
        <Parameter Name="PREDVAL" EqualsSign="None" ParameterType="Keyword"/>
        <Parameter Name="PREDPROB" EqualsSign="None" ParameterType="Keyword"/>
    </Subcommand>
    <Subcommand Name="OUTFILE" EqualsSign="None">
        <Parameter Name="MODEL" EqualsSign="Optional" ParameterType="Keyword"/>
    </Subcommand>
</Command>

=== muhammadmisbah/SPSSexe-installed-pckg/IBM/SPSS/Statistics/21/syntax_xml/TMS IMPORT.xml
<?xml version="1.0"?>
<!-- ***************************************************************** -->
<!--                                                                   -->
<!-- Licensed Materials - Property of IBM                              -->
<!--                                                                   -->
<!-- IBM SPSS Products: Statistics Common                              -->
<!--                                                                   -->
<!-- (C) Copyright IBM Corp. 1989, 2011                                -->
<!--                                                                   -->
<!-- US Government Users Restricted Rights - Use, duplication or       -->
<!-- disclosure restricted by GSA ADP Schedule Contract with IBM       -->
<!-- Corp.                                                             -->
<!--                                                                   -->
<!-- ***************************************************************** -->


<Command xmlns="http://xml.spss.com/spss/extension"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://xml.spss.com/spss/extension http://xml.spss.com/spss/extension/SyntaxSchema.xsd"
    xmlns:p1="http://xml.spss.com/spss/extension" Name="TMS IMPORT" EndRequired="None"
    IsArbitrary="No" Language="Syntax">
    <Subcommand Name="INFILE">
        <Parameter Name="TRANSFORMATIONS" EqualsSign="Required" ParameterType="Keyword"/>
        <Parameter Name="MODE" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="FORWARD"/>
            <EnumValue Name="ROLES"/>
            <EnumValue Name="UPDATE"/>
            <EnumValue Name="LEAVE"/>
            <EnumValue Name="BACK"/>
            <EnumValue Name="PREDICTED"/>
            <EnumValue Name="SUFFIX"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="SAVE">
        <Parameter Name="TRANSFORMED" EqualsSign="Required" ParameterType="Keyword">
            <EnumValue Name="YES"/>
            <EnumValue Name="NO"/>
        </Parameter>
    </Subcommand>
    <Subcommand Name="OUTFILE">
        <Parameter Name="SYNTAX" EqualsSign="Required" ParameterType="Keyword"/>
    </Subcommand>
</Command>
